/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uclab.ui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Date;
import javax.swing.JFrame;
import network.NetworkHandler;
import uclab.common.TextFileWrite;
import uclab.algorithms.ECG_SignalRunnable;

/**
 *
 * @author train
 */
public class ResultJFrame extends javax.swing.JFrame {

    ECG_SignalRunnable ecgSignal;
    TextFileWrite<Double> textFile;
    String app_AfResult = null, doctor_AfResult = null;
    /**
     * Creates new form ResultJFrame
     */
    public ResultJFrame(ECG_SignalRunnable ecgSignal, String afResult) {
            System.out.println("ResultFrame");
        initComponents();
        //현재 프레임만 종료
        genderButtonGroup.add(maleRadioBtn);
        genderButtonGroup.add(femaleRadioBtn);
        DiagnosisButtonGroup.add(VPCRadioBtn);
        DiagnosisButtonGroup.add(nsrRadioBtn);
        DiagnosisButtonGroup.add(apcRadioBtn);
        DiagnosisButtonGroup.add(afRadioBtn);
        DiagnosisButtonGroup.add(aflRadioBtn);
        DiagnosisButtonGroup.add(etcRadioBtn);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        String ss = ecgSignal.simbaksu;
        
        this.app_AfResult = afResult;
        this.ecgSignal = ecgSignal;
        textFile = new TextFileWrite<Double>("Diagnosis_result", "rawEcg");
        
         this.addWindowListener(new WindowAdapter(){
            public void windowClosing(WindowEvent e){
             System.out.println("resultFrame closing");      
             e.getWindow().dispose();
            }         
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        DiagnosisButtonGroup = new javax.swing.ButtonGroup();
        SmokingButtonGroup = new javax.swing.ButtonGroup();
        resultPanel = new javax.swing.JPanel();
        genderText = new javax.swing.JTextField();
        ageText = new javax.swing.JTextField();
        resultTitleText = new javax.swing.JTextField();
        maleRadioBtn = new javax.swing.JRadioButton();
        femaleRadioBtn = new javax.swing.JRadioButton();
        nsrRadioBtn = new javax.swing.JRadioButton();
        afRadioBtn = new javax.swing.JRadioButton();
        aflRadioBtn = new javax.swing.JRadioButton();
        apcRadioBtn = new javax.swing.JRadioButton();
        VPCRadioBtn = new javax.swing.JRadioButton();
        resultSaveBtn = new javax.swing.JButton();
        ageEdit = new javax.swing.JEditorPane();
        etcRadioBtn = new javax.swing.JRadioButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        etcEdit = new javax.swing.JEditorPane();
        nonsmokerRadioBtn = new javax.swing.JRadioButton();
        smokerRadioBtn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        resultPanel.setBackground(new java.awt.Color(255, 255, 255));

        genderText.setFont(new java.awt.Font("210 맨발의청춘 B", 1, 30)); // NOI18N
        genderText.setText("Gender");
        genderText.setBorder(null);
        genderText.setCaretColor(new java.awt.Color(255, 255, 255));
        genderText.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        genderText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderTextActionPerformed(evt);
            }
        });

        ageText.setFont(new java.awt.Font("210 맨발의청춘 B", 1, 30)); // NOI18N
        ageText.setText("Age");
        ageText.setBorder(null);

        resultTitleText.setEditable(false);
        resultTitleText.setBackground(new java.awt.Color(255, 255, 255));
        resultTitleText.setFont(new java.awt.Font("210 맨발의청춘 B", 0, 30)); // NOI18N
        resultTitleText.setText("Diagnosis Result");
        resultTitleText.setBorder(null);
        resultTitleText.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        maleRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        maleRadioBtn.setFont(new java.awt.Font("210 맨발의청춘 B", 1, 30)); // NOI18N
        maleRadioBtn.setText("Male");
        maleRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioBtnActionPerformed(evt);
            }
        });

        femaleRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        femaleRadioBtn.setFont(new java.awt.Font("210 맨발의청춘 B", 1, 30)); // NOI18N
        femaleRadioBtn.setText("Female");
        femaleRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioBtnActionPerformed(evt);
            }
        });

        nsrRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        nsrRadioBtn.setFont(new java.awt.Font("210 맨발의청춘 B", 1, 30)); // NOI18N
        nsrRadioBtn.setText("NSR");

        afRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        afRadioBtn.setFont(new java.awt.Font("210 맨발의청춘 B", 1, 30)); // NOI18N
        afRadioBtn.setText("AF");
        afRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afRadioBtnActionPerformed(evt);
            }
        });

        aflRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        aflRadioBtn.setFont(new java.awt.Font("210 맨발의청춘 B", 1, 30)); // NOI18N
        aflRadioBtn.setText("AFL");
        aflRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aflRadioBtnActionPerformed(evt);
            }
        });

        apcRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        apcRadioBtn.setFont(new java.awt.Font("210 맨발의청춘 B", 1, 30)); // NOI18N
        apcRadioBtn.setText("APC");
        apcRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apcRadioBtnActionPerformed(evt);
            }
        });

        VPCRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        VPCRadioBtn.setFont(new java.awt.Font("210 맨발의청춘 B", 1, 30)); // NOI18N
        VPCRadioBtn.setText("VPC");
        VPCRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VPCRadioBtnActionPerformed(evt);
            }
        });

        resultSaveBtn.setBackground(new java.awt.Color(255, 255, 255));
        resultSaveBtn.setFont(new java.awt.Font("210 맨발의청춘 B", 1, 30)); // NOI18N
        resultSaveBtn.setText("SAVE");
        resultSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultSaveBtnActionPerformed(evt);
            }
        });

        ageEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ageEdit.setFont(new java.awt.Font("굴림", 0, 36)); // NOI18N

        etcRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        etcRadioBtn.setFont(new java.awt.Font("210 맨발의청춘 B", 1, 30)); // NOI18N
        etcRadioBtn.setText("ETC");
        etcRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etcRadioBtnActionPerformed(evt);
            }
        });

        etcEdit.setFont(new java.awt.Font("굴림", 0, 36)); // NOI18N
        jScrollPane5.setViewportView(etcEdit);

        nonsmokerRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        nonsmokerRadioBtn.setFont(new java.awt.Font("210 맨발의청춘 B", 1, 30)); // NOI18N
        nonsmokerRadioBtn.setText("Nonsmoker");

        smokerRadioBtn.setBackground(new java.awt.Color(255, 255, 255));
        smokerRadioBtn.setFont(new java.awt.Font("210 맨발의청춘 B", 1, 30)); // NOI18N
        smokerRadioBtn.setText("Smoker");

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resultPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(etcRadioBtn)
                            .addGroup(resultPanelLayout.createSequentialGroup()
                                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(resultPanelLayout.createSequentialGroup()
                                        .addComponent(nsrRadioBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(afRadioBtn))
                                    .addComponent(smokerRadioBtn))
                                .addGap(18, 18, 18)
                                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(resultPanelLayout.createSequentialGroup()
                                        .addComponent(aflRadioBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(apcRadioBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(VPCRadioBtn))
                                    .addComponent(nonsmokerRadioBtn)))
                            .addGroup(resultPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(genderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addComponent(maleRadioBtn)
                                .addGap(18, 18, 18)
                                .addComponent(femaleRadioBtn))
                            .addComponent(jScrollPane5)))
                    .addGroup(resultPanelLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(ageEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(resultPanelLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(resultTitleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(resultPanelLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(resultSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(resultTitleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(femaleRadioBtn)
                    .addComponent(maleRadioBtn))
                .addGap(26, 26, 26)
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ageText, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(ageEdit))
                .addGap(18, 18, 18)
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apcRadioBtn)
                    .addComponent(afRadioBtn)
                    .addComponent(aflRadioBtn)
                    .addComponent(nsrRadioBtn)
                    .addComponent(VPCRadioBtn))
                .addGap(26, 26, 26)
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smokerRadioBtn)
                    .addComponent(nonsmokerRadioBtn))
                .addGap(18, 18, 18)
                .addComponent(etcRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(resultSaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(resultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(24, 24, 24)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(resultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void genderTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderTextActionPerformed

    private void maleRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioBtnActionPerformed
        // TODO add your handling code here:
        //        System.outjRadioButton1.getText();
    }//GEN-LAST:event_maleRadioBtnActionPerformed

    private void femaleRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleRadioBtnActionPerformed

    private void afRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_afRadioBtnActionPerformed

    private void aflRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aflRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aflRadioBtnActionPerformed

    private void apcRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apcRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apcRadioBtnActionPerformed

    private void VPCRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VPCRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VPCRadioBtnActionPerformed

    private void resultSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultSaveBtnActionPerformed
        // TODO add your handling code here:
        String gender = null, smoke = null, etc = null;
        String age = null;

        if(maleRadioBtn.isSelected()){
            gender = "male";
        }
        if(femaleRadioBtn.isSelected()){
            gender = "female";
        }
        if(nsrRadioBtn.isSelected()){
            doctor_AfResult = "NSR";
        }
        if(apcRadioBtn.isSelected()){
            doctor_AfResult = "APC";
        }
        if(VPCRadioBtn.isSelected()){
            doctor_AfResult = "VPC";
        }
        if(afRadioBtn.isSelected()){
            doctor_AfResult = "AF";
        }
        if(aflRadioBtn.isSelected()){
            doctor_AfResult = "AFL";
        }
   
        if(smokerRadioBtn.isSelected()){
            smoke = "smoker";
        }
        if(nonsmokerRadioBtn.isSelected()){
            smoke = "nonsmoker";
        }
        
        etc = "ETC:" + etcEdit.getText().toString();
        age = ageEdit.getText().toString();

        long time = System.currentTimeMillis();

        //        SimpleDateFormat dayTime = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");
        Date dateClass = new Date(time);
        //        dayTime.
        int year = dateClass.getYear();
        int day = dateClass.getDate();
        int month = dateClass.getMonth();
        int hour = dateClass.getHours();
        int minute = dateClass.getMinutes();
        int sec = dateClass.getSeconds();
        int date = dateClass.getDate();

        System.out.println(month+","+date+","+day+","+hour+","+minute+","+sec);
        //        FileWriter fp = new FileWriter()

        textFile = new TextFileWrite<Double>("Diagnosis_result", year+"_"+month+"_"+day+"_"+date+"_"+hour+"_"+minute+"_"+sec+"_"+gender);
        System.out.println(gender+","+age+","+ "weight:"+UiUpdateRunnable.weightText+", Doctor AF Diagnosis"+doctor_AfResult +","+smoke+","+etc+", APP AF Diagnosis"+app_AfResult);
        //진단결과 넣기
        textFile.add(gender+","+age+","+ "weight:"+UiUpdateRunnable.weightText+", Doctor AF Diagnosis"+doctor_AfResult +","+smoke+","+etc+", APP AF Diagnosis"+app_AfResult);
        double[] data = new double[ecgSignal.clean_signal.size()];
        for(int n = 0; n  < ecgSignal.clean_signal.size(); n++){
            data[n] = ecgSignal.clean_signal.get(n);
        }
        textFile.add(data);
        
        //주환 수정
        if(app_AfResult.equals("yes")){
            NetworkHandler.dataAdd("yes", UiUpdateRunnable.weightText,ecgSignal.simbaksu);   
        }else{
            NetworkHandler.dataAdd("no", UiUpdateRunnable.weightText,ecgSignal.simbaksu);   
        }        

//        if(gender == null || doctor_AfResult == null || age == null){
//
//        }else{

             System.out.println("resultFrame closing");      
            this.dispose();
//            //            System.exit(0);
//        }
    }//GEN-LAST:event_resultSaveBtnActionPerformed

    private void etcRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etcRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etcRadioBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup DiagnosisButtonGroup;
    private javax.swing.ButtonGroup SmokingButtonGroup;
    private javax.swing.JRadioButton VPCRadioBtn;
    private javax.swing.JRadioButton afRadioBtn;
    private javax.swing.JRadioButton aflRadioBtn;
    private javax.swing.JEditorPane ageEdit;
    private javax.swing.JTextField ageText;
    private javax.swing.JRadioButton apcRadioBtn;
    private javax.swing.JEditorPane etcEdit;
    private javax.swing.JRadioButton etcRadioBtn;
    private javax.swing.JRadioButton femaleRadioBtn;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JTextField genderText;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JRadioButton maleRadioBtn;
    private javax.swing.JRadioButton nonsmokerRadioBtn;
    private javax.swing.JRadioButton nsrRadioBtn;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JButton resultSaveBtn;
    private javax.swing.JTextField resultTitleText;
    private javax.swing.JRadioButton smokerRadioBtn;
    // End of variables declaration//GEN-END:variables
}
